{% set name = "viztracer" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/viztracer-{{ version }}.tar.gz
  sha256: 46216ef86808cb6212885ee9965ead2cc98809ba20a6f7c3282ea8b2ed7ef4a9

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - viztracer = viztracer:main
    - vdb = viztracer:sim_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python
    - rich
    - orjson

test:
  imports:
    - viztracer
  commands:
    - pip check
    - viztracer --help
    - vdb --help
  requires:
    - pip

about:
  home: https://github.com/gaogaotiantian/viztracer
  summary: A debugging and profiling tool that can trace and visualize python code execution
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
